services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0
    ports:
      - 18888:18888 # The web interface for the dashboard
      - 18889:18889 # The OTLP receiver for the dashboard
    environment:
      Dashboard__Frontend__AuthMode: Unsecured

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config", "/etc/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    env_file:
      - .env
    ports:
      - 4317:4317
    depends_on:
      - aspire-dashboard