receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  datadog:
    api:
      site: datadoghq.com
      key: ${DD_API_KEY}
    metrics:
      sums:
        cumulative_monotonic_mode: "to_delta"
      summaries:
        mode: "gauges"
    traces: {}

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
